version: '3'

networks:
  app-tier:
    driver: bridge

services:
  postgres:
    image: docker.io/citusdata/citus:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-tier
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=*Abcd123456
      - POSTGRES_DB=loft
    logging:
      options:
        max-size: '500m'

  jaeger:
    image: docker.io/jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "6831:6831/udp"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    networks:
      - app-tier
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    logging:
      options:
        max-size: '500m'

  etcd:
    image: "bitnami/etcd:latest"
    container_name: etcd
    ports:
      - "4001:4001"
      - "2380:2380"
      - "2379:2379"
    environment:
      - ETCD_NAME=etcd0
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379,http://127.0.0.1:4001
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://127.0.0.1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-1
      - ETCD_INITIAL_CLUSTER=etcd0=http://127.0.0.1:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ALLOW_NONE_AUTHENTICATION=yes
    restart: always

  dtm:
    image: "yedf/dtm"
    container_name: dtm
    networks:
      - default
    environment:
#      STORE_DRIVER: redis
#      STORE_HOST: 127.0.0.1
#      STORE_USER:
#      STORE_PASSWORD:
#      STORE_PORT: 6379
      MICRO_SERVICE_DRIVER: "dtm-driver-kratos"
      MICRO_SERVICE_TARGET: "etcd://127.0.0.1:2379/dtmservice"
      MICRO_SERVICE_END_POINT: "grpc://127.0.0.1:36790"
    ports:
      - '36789:36789'
      - '36790:36790'
    restart: always
